"""
Convert JSONL training data to Parquet format for verl.

This script converts the JSONL data generated by create_data.py into
Parquet format that verl's MultiTurnSFTDataset can read.
"""

import argparse
import json
import pandas as pd
from pathlib import Path


def convert_jsonl_to_parquet(input_file: str, output_file: str):
    """
    Convert JSONL file to Parquet format.
    
    Args:
        input_file: Path to input JSONL file
        output_file: Path to output Parquet file
    """
    print(f"Reading JSONL file: {input_file}")
    
    # Read JSONL file
    data = []
    with open(input_file, "r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                data.append(json.loads(line))
    
    print(f"Loaded {len(data)} records")
    
    # Convert to DataFrame
    df = pd.DataFrame(data)
    
    print(f"DataFrame shape: {df.shape}")
    print(f"DataFrame columns: {df.columns.tolist()}")
    
    # Show sample
    if len(df) > 0:
        print(f"\nSample record:")
        print(df.iloc[0].to_dict())
    
    # Save as Parquet
    print(f"\nSaving to Parquet: {output_file}")
    df.to_parquet(output_file, engine="pyarrow", compression="snappy")
    
    print(f"✅ Conversion complete!")
    print(f"   Input:  {input_file} ({len(data)} records)")
    print(f"   Output: {output_file}")
    
    # Verify the file can be read
    print(f"\nVerifying Parquet file...")
    df_verify = pd.read_parquet(output_file)
    print(f"   Successfully read {len(df_verify)} records from Parquet file")


def main():
    parser = argparse.ArgumentParser(
        description="Convert JSONL training data to Parquet format for verl"
    )
    parser.add_argument(
        "--input_file",
        type=str,
        default="./data/prompt_distillation_lang.jsonl",
        help="Path to input JSONL file",
    )
    parser.add_argument(
        "--output_file",
        type=str,
        default="./data/prompt_distillation_lang.parquet",
        help="Path to output Parquet file",
    )
    
    args = parser.parse_args()
    
    # Check if input file exists
    if not Path(args.input_file).exists():
        raise FileNotFoundError(f"Input file not found: {args.input_file}")
    
    # Create output directory if needed
    output_dir = Path(args.output_file).parent
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Convert
    convert_jsonl_to_parquet(args.input_file, args.output_file)


if __name__ == "__main__":
    main()

